<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomeField2</name>
   <tag></tag>
   <elementGuidId>d9e126cf-486c-458c-b8d2-8266b51436fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='tab-pane section-details clearfix active']//a[@name='CustomField2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable editable-pre-wrapped editable-click</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomField2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>inline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-emptytext</name>
      <type>Main</type>
      <value>None</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3554422345</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;medium wf-roboto-n7-active wf-roboto-n4-active wf-adellesans-n7-active wf-adellesans-n4-active wf-roboto-n5-active wf-roboto-i5-active wf-roboto-i7-active wf-roboto-i4-active wf-active windowsos chrome&quot;]/body[1]/div[@class=&quot;modal order-detail in first-order&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane section-details clearfix active&quot;]/div[@class=&quot;col-sm-12 col-md-8&quot;]/div[@class=&quot;module order-notes&quot;]/div[@class=&quot;notes lite-pad&quot;]/table[@class=&quot;prop-table order-notes&quot;]/tbody[1]/tr[6]/td[1]/a[@class=&quot;editable editable-pre-wrapped editable-click&quot;]</value>
   </webElementProperties>
</WebElementEntity>
