<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spinner</name>
   <tag></tag>
   <elementGuidId>7a94db7a-ce95-4815-b560-ae2929c2f9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.pageOverlay_spinner</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
